apiVersion: v1
kind: Pod
metadata:
  name: meupod
spec:
  containers:
    - name: web
      image: mailvolpe/conversao-temperatura:v1
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: meupod2
  labels:
    app: green
spec:
  containers:
    - name: web
      image: mailvolpe/conversao-temperatura:v2
      ports:
        - containerPort: 8080